2025-06-02 20:45:55.329  INFO 16077 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 16077 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-02 20:45:55.333 DEBUG 16077 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-02 20:45:55.334  INFO 16077 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-02 20:45:55.866 DEBUG 16077 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-02 20:45:56.800  INFO 16077 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.637 seconds (JVM running for 2.104)
2025-06-02 20:46:32.025  INFO 16077 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.controllers.LoginController : Processing login: dario with pwd dario
2025-06-02 20:46:32.078  INFO 16077 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.UserService : com.aciworldwide.aclabs22.entities.UserModel@7aa0d1c3
2025-06-02 20:46:33.801 ERROR 16077 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-02 20:46:33.801 ERROR 16077 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 38, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 34, in main    anomalies = detect_anomalies(transactions)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in detect_anomalies    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-02 20:46:54.914  INFO 16077 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=15000.0, timestamp=2025-06-02 20:46:54.904)
2025-06-02 20:46:54.926  INFO 16077 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-02 20:46:54.944  INFO 16077 --- [nio-8080-exec-6] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 3131
2025-06-02 20:47:03.512 ERROR 16077 --- [nio-8080-exec-9] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-02 20:47:03.512 ERROR 16077 --- [nio-8080-exec-9] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 38, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 34, in main    anomalies = detect_anomalies(transactions)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in detect_anomalies    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-02 20:47:25.314  INFO 16077 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=33500.0, timestamp=2025-06-02 20:47:25.309)
2025-06-02 20:47:25.319  INFO 16077 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-02 20:47:25.329  INFO 16077 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 3132
2025-06-02 20:47:28.710 ERROR 16077 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-02 20:47:28.710 ERROR 16077 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 38, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 34, in main    anomalies = detect_anomalies(transactions)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in detect_anomalies    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-02 20:47:31.359 ERROR 16077 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-02 20:47:31.359 ERROR 16077 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 38, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 34, in main    anomalies = detect_anomalies(transactions)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in detect_anomalies    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-02 20:48:26.516 ERROR 16077 --- [io-8080-exec-10] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 1
2025-06-02 20:48:26.516 ERROR 16077 --- [io-8080-exec-10] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: Traceback (most recent call last):  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 38, in <module>    main()  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 34, in main    anomalies = detect_anomalies(transactions)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/model/predict.py", line 8, in detect_anomalies    model = joblib.load('model.pkl')            ^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/anaconda3/lib/python3.12/site-packages/joblib/numpy_pickle.py", line 650, in load    with open(filename, 'rb') as f:         ^^^^^^^^^^^^^^^^^^^^FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
2025-06-02 20:56:08.649  INFO 16280 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 16280 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-02 20:56:08.652 DEBUG 16280 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-02 20:56:08.652  INFO 16280 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-02 20:56:09.108 DEBUG 16280 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-02 20:56:09.893  INFO 16280 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.462 seconds (JVM running for 1.98)
2025-06-02 20:58:24.518  INFO 16280 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=20.0, timestamp=2025-06-02 20:58:24.498)
2025-06-02 20:58:24.532  INFO 16280 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-02 20:58:24.547  INFO 16280 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 3133
2025-06-02 20:58:40.776  INFO 16280 --- [nio-8080-exec-7] com.aciworldwide.aclabs22.controllers.TransactionController : Received transaction request: TransactionDTO(cardNumber=1234567812345670, amount=20000.0, timestamp=2025-06-02 20:58:40.77)
2025-06-02 20:58:40.780  INFO 16280 --- [nio-8080-exec-7] com.aciworldwide.aclabs22.helpers.ValidationHelper : Validation succeeded with status: APPROVED and message: Transaction approved
2025-06-02 20:58:40.807  INFO 16280 --- [nio-8080-exec-7] com.aciworldwide.aclabs22.services.TransactionService : Transaction saved: 3134
2025-06-02 21:08:14.627  INFO 16394 --- [           main] com.aciworldwide.aclabs22.Aclabs22ApplicationTests : Starting Aclabs22ApplicationTests using Java 24 on Darios-MacBook-Pro.local with PID 16394 (started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-02 21:08:14.630 DEBUG 16394 --- [           main] com.aciworldwide.aclabs22.Aclabs22ApplicationTests : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-02 21:08:14.630  INFO 16394 --- [           main] com.aciworldwide.aclabs22.Aclabs22ApplicationTests : No active profile set, falling back to default profiles: default
2025-06-02 21:08:16.087  INFO 16394 --- [           main] com.aciworldwide.aclabs22.Aclabs22ApplicationTests : Started Aclabs22ApplicationTests in 1.554 seconds (JVM running for 2.078)
2025-06-02 21:37:57.744  INFO 17258 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 17258 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-02 21:37:57.746 DEBUG 17258 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-02 21:37:57.747  INFO 17258 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-02 21:37:58.225 DEBUG 17258 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-02 21:37:59.134  INFO 17258 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.515 seconds (JVM running for 1.944)
2025-06-02 21:38:06.714 ERROR 17258 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 2
2025-06-02 21:38:06.715 ERROR 17258 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: python3: can't open file '/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/../../../../../model/predict.py': [Errno 2] No such file or directory
2025-06-02 21:38:09.382 ERROR 17258 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 2
2025-06-02 21:38:09.382 ERROR 17258 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: python3: can't open file '/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/../../../../../model/predict.py': [Errno 2] No such file or directory
2025-06-02 21:38:18.557  INFO 17258 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.controllers.LoginController : Processing login: dario with pwd dario
2025-06-02 21:38:18.566  INFO 17258 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.UserService : com.aciworldwide.aclabs22.entities.UserModel@38e786ee
2025-06-02 21:38:19.671 ERROR 17258 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 2
2025-06-02 21:38:19.671 ERROR 17258 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: python3: can't open file '/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/../../../../../model/predict.py': [Errno 2] No such file or directory
2025-06-02 21:39:06.512  INFO 17336 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 17336 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-02 21:39:06.516 DEBUG 17336 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-02 21:39:06.517  INFO 17336 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-02 21:39:07.050 DEBUG 17336 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-02 21:39:07.829  INFO 17336 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.485 seconds (JVM running for 1.876)
2025-06-02 21:39:26.933  INFO 17354 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 17354 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-02 21:39:26.935 DEBUG 17354 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-02 21:39:26.935  INFO 17354 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-02 21:39:27.419 DEBUG 17354 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-02 21:39:28.251  INFO 17354 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.426 seconds (JVM running for 1.845)
2025-06-02 21:39:33.968 ERROR 17354 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 2
2025-06-02 21:39:33.968 ERROR 17354 --- [nio-8080-exec-1] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: python3: can't open file '/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/main/java/com/aciworldwide/aclabs22/services/../../../model/predict.py': [Errno 2] No such file or directory
2025-06-02 21:39:35.639 ERROR 17354 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 2
2025-06-02 21:39:35.639 ERROR 17354 --- [nio-8080-exec-2] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: python3: can't open file '/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/main/java/com/aciworldwide/aclabs22/services/../../../model/predict.py': [Errno 2] No such file or directory
2025-06-02 21:39:37.890 ERROR 17354 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 2
2025-06-02 21:39:37.890 ERROR 17354 --- [nio-8080-exec-3] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: python3: can't open file '/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/main/java/com/aciworldwide/aclabs22/services/../../../model/predict.py': [Errno 2] No such file or directory
2025-06-02 21:40:06.383 ERROR 17354 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 2
2025-06-02 21:40:06.383 ERROR 17354 --- [nio-8080-exec-4] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: python3: can't open file '/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/main/java/com/aciworldwide/aclabs22/services/../../../model/predict.py': [Errno 2] No such file or directory
2025-06-02 21:40:14.739 ERROR 17354 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.AnomalyService : Python script exited with code 2
2025-06-02 21:40:14.739 ERROR 17354 --- [nio-8080-exec-5] com.aciworldwide.aclabs22.services.AnomalyService : Output/Error: python3: can't open file '/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/src/main/java/com/aciworldwide/aclabs22/services/../../../model/predict.py': [Errno 2] No such file or directory
2025-06-02 21:40:47.555  INFO 17373 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 17373 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-02 21:40:47.557 DEBUG 17373 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-02 21:40:47.557  INFO 17373 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-02 21:40:48.020 DEBUG 17373 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
2025-06-02 21:40:48.805  INFO 17373 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Started Aclabs22Application in 1.362 seconds (JVM running for 1.743)
2025-06-02 22:12:41.971  INFO 17498 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Starting Aclabs22Application using Java 24 on Darios-MacBook-Pro.local with PID 17498 (/Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST/target/classes started by dariofriskan in /Users/dariofriskan/Documents/ACI-LigaACLabs2023-REST)
2025-06-02 22:12:41.973 DEBUG 17498 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : Running with Spring Boot v2.6.3, Spring v5.3.15
2025-06-02 22:12:41.973  INFO 17498 --- [           main] com.aciworldwide.aclabs22.Aclabs22Application : No active profile set, falling back to default profiles: default
2025-06-02 22:12:42.319 DEBUG 17498 --- [           main] com.aciworldwide.aclabs22.utils.JWTAuthenticationFilter : Filter 'JWTAuthenticationFilter' configured for use
